// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muinapoxedpizstmffwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11aW5hcG94ZWRwaXpzdG1mZndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjgzMDEsImV4cCI6MjA3NDA0NDMwMX0.R4xfAMnPDoDp23PhUzGd3KyS4SB-U-FbznlulcX9sOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});